version: '3'

dotenv: ['.env']

env:
  DEFAULT_TITLE: openai_learnings
  DEFAULT_REGION: "eastus2"

includes:
  docintel: 
    taskfile: ./infrastructure/document-intelligence/Taskfile.yaml
    internal: false
    dir: ./infrastructure/document-intelligence/

  openai: 
    taskfile: ./infrastructure/openai/Taskfile.yaml
    internal: false
    dir: ./infrastructure/openai/

  ai-hub: 
    taskfile: ./infrastructure/ai-hub/Taskfile.yaml
    internal: false
    dir: ./infrastructure/ai-hub/    

  simple: 
    taskfile: ./infrastructure/ai-foundry/Taskfile.yaml
    internal: false
    dir: ./infrastructure/ai-foundry/    

  classic: 
    taskfile: ./infrastructure/agent-service-classic/Taskfile.yaml
    internal: false
    dir: ./infrastructure/agent-service-classic/

  agents: 
    taskfile: ./infrastructure/agent-service/Taskfile.yaml
    internal: false
    dir: ./infrastructure/agent-service/

tasks:
  default: 
    cmds: 
    - task --list 
  
  otel:
    desc: Semantic Kernel with Observability
    dir: ./src/ric_analyzer_with_observability
    cmds:
    - docker run --rm -p 18888:18888 -p 4317:18889 -d --name aspire-dashboard  mcr.microsoft.com/dotnet/aspire-dashboard:8.1.0 > /dev/null 2>&1 || true
    - cmd: dotnet run
      silent: true
    - task: aspire-dashboard
  
  aspire-dashboard:
    desc: Gets Login Info for Aspire
    cmds:
    - cmd: echo Check Aspire Dashboard at {{.URL}} for more details
      silent: true
    vars:
      URL:
        sh: docker logs aspire-dashboard | grep -i "Login to the dashboard at" | awk '{print $6}' | sed 's/0\.0\.0\.0/localhost/'
