version: '3'

env:
  AIF_STANDARD_TITLE: "AI Foundry - BYO Components Demo"

tasks:
  default: 
    cmds: 
    - task --list 
  
  up: 
    desc: Builds a Complete {{.AIF_STANDARD_TITLE}} Environment
    cmds:
    - task: init
    - task: apply 

  init:
    desc: Initializes Terraform workspace
    cmds:
    - terraform workspace new {{.REGION}} || true
    - terraform workspace select {{.REGION}}
    - terraform init
    vars: 
      REGION: '{{default .DEFAULT_REGION .CLI_ARGS}}'

  apply:
    desc: Creates Azure infrastructure
    cmds:
    - terraform apply -auto-approve
      -var "region={{.REGION}}" 
      -var "tags={{.AIF_STANDARD_TITLE}}"
      -compact-warnings
    vars: 
      REGION: '{{default .DEFAULT_REGION .CLI_ARGS}}'

  refresh:
    cmds:
    - terraform refresh
      -var "region={{.REGION}}" 
      -var "tags={{.AIF_STANDARD_TITLE}}"
      -compact-warnings
    vars: 
      REGION: '{{default .DEFAULT_REGION .CLI_ARGS}}'

  down:
    desc: Destroys all Azure resources and cleans up Terraform
    cmds:       
    - terraform destroy -var "region={{.REGION}}" -var "tags={{.AIF_STANDARD_TITLE}}" -compact-warnings || true
    - rm -rf terraform.tfstate.d .terraform.lock.hcl .terraform terraform.tfstate terraform.tfstate.backup .terraform.tfstate.lock.info || true
    vars: 
      REGION: '{{default .DEFAULT_REGION .CLI_ARGS}}'
