kind: workflow
trigger:
  kind: OnConversationStart
  id: trigger_wf
  actions:
    - kind: InvokeAzureAgent
      id: agent1
      agent:
        name: "007"
      description: First agent in sequential workflow
      conversationId: =System.ConversationId
      input:
        messages: =System.LastMessage
      output:
        messages: Local.LatestMessage
        autoSend: true
    - kind: InvokeAzureAgent
      id: agent2
      agent:
        name: M
      conversationId: =System.ConversationId
      description: Second agent in sequential workflow
      input:
        messages: =Local.LatestMessage
      output:
        messages: Local.LatestMessage
        autoSend: true
id: ""
name: expense-reports
description: ""

# using Azure.AI.Projects;
# using Azure.AI.Projects.OpenAI;
# using Azure.Identity;
# using OpenAI;
# using OpenAI.Responses;

# #pragma warning disable OPENAI001

# const string projectEndpoint = "https://impala-11556-foundry.services.ai.azure.com/api/projects/impala-11556-project";
# const string agentName = "expense-reports";
# const string agentVersion = "1";
# const string userMessage = "Hi expense-reports";

# AIProjectClient projectClient = new(endpoint: new Uri(projectEndpoint), tokenProvider: new DefaultAzureCredential());

# ProjectConversation conversation = projectClient.OpenAI.Conversations.CreateProjectConversation();
# AgentReference agentReference = new AgentReference(name: agentName, version: agentVersion);
# ProjectResponsesClient responseClient = projectClient.OpenAI.GetProjectResponsesClientForAgent(agentReference, conversation.Id);

# ResponseResult response = responseClient.CreateResponse(userMessage);
# Console.WriteLine(response.GetOutputText());